


Exercise on Functions:

**Task - 1:**

Create a Python program that converts between different units of measurement.
*   The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
*   Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.
*   Conversion Options:
1. Length:
- Convert meters (m) to feet (ft).
- Convert feet (ft) to meters (m).
2. Weight:
- Convert kilograms (kg) to pounds (lbs).
- Convert pounds (lbs) to kilograms (kg).
3. Volume:
- Convert liters (L) to gallons (gal).
- Convert gallons (gal) to liters (L).


In [2]:
def length_conversion(amount, source_unit, target_unit):
  """
  Converts length between meters (m) and feet (ft).
  """
  unit_options = {'m', 'ft'}
  if source_unit not in unit_options or target_unit not in unit_options:
    raise ValueError("Invalid units. Choose 'm' or 'ft'.")

  if source_unit == 'm' and target_unit == 'ft':
    return amount * 3.28084
  elif source_unit == 'ft' and target_unit == 'm':
    return amount / 3.28084
  else:
    raise ValueError("Invalid conversion units.")

def weight_conversion(amount, source_unit, target_unit):
  """
  Converts weight between kilograms (kg) and pounds (lbs).
  """
  unit_options = {'kg', 'lbs'}
  if source_unit not in unit_options or target_unit not in unit_options:
    raise ValueError("Invalid units. Choose 'kg' or 'lbs'.")

  if source_unit == 'kg' and target_unit == 'lbs':
    return amount * 2.20462
  elif source_unit == 'lbs' and target_unit == 'kg':
    return amount / 2.20462
  else:
    raise ValueError("Invalid conversion units.")

def volume_conversion(amount, source_unit, target_unit):
  """
  Converts volume between liters (l) and gallons (gal).
  """
  unit_options = {'l', 'gal'}
  if source_unit not in unit_options or target_unit not in unit_options:
    raise ValueError("Invalid units. Choose 'l' or 'gal'.")

  if source_unit == 'l' and target_unit == 'gal':
    return amount * 0.264172
  elif source_unit == 'gal' and target_unit == 'l':
    return amount / 0.264172
  else:
    raise ValueError("Invalid conversion units.")

def run_conversion():
  """
  Main function for unit conversion program.
  """
  while True:
    print("\nAvailable Conversion Types:")
    print("1. Length (m/ft)")
    print("2. Weight (kg/lbs)")
    print("3. Volume (l/gal)")

    try:
      option = int(input("\nEnter a number (1-3) to select conversion or 4 to quit: "))

      if option == 4:
        print("Closing program.")
        break

      if option not in [1, 2, 3]:
        raise ValueError("Invalid selection. Choose a valid option.")

      while True:
        try:
          amount = float(input("Enter the numerical value to convert: "))
          if amount <= 0:
            print("Error: Input must be a positive number.")
            continue
          break
        except ValueError:
          print("Error: Enter a valid numeric value.")

      if option == 1:
        source_unit = input("Enter source unit (m or ft): ").lower()
        target_unit = input("Enter target unit (m or ft): ").lower()
        output = length_conversion(amount, source_unit, target_unit)

      elif option == 2:
        source_unit = input("Enter source unit (kg or lbs): ").lower()
        target_unit = input("Enter target unit (kg or lbs): ").lower()
        output = weight_conversion(amount, source_unit, target_unit)

      elif option == 3:
        source_unit = input("Enter source unit (l or gal): ").lower()
        target_unit = input("Enter target unit (l or gal): ").lower()
        output = volume_conversion(amount, source_unit, target_unit)

      print(f"\nConversion Result: {amount} {source_unit} is equivalent to {output:.2f} {target_unit}.")
    except ValueError as err:
      print(f"Error: {err}")
    except Exception as err:
      print(f"Unexpected issue: {err}")

run_conversion()



Available Conversion Types:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter a number (1-3) to select conversion or 4 to quit: 5
Error: Invalid selection. Choose a valid option.

Available Conversion Types:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter a number (1-3) to select conversion or 4 to quit: 3
Enter the numerical value to convert: 200
Enter source unit (l or gal): gal
Enter target unit (l or gal): l

Conversion Result: 200.0 gal is equivalent to 757.08 l.

Available Conversion Types:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter a number (1-3) to select conversion or 4 to quit: 2
Enter the numerical value to convert: 165
Enter source unit (kg or lbs): kg
Enter target unit (kg or lbs): lbs

Conversion Result: 165.0 kg is equivalent to 363.76 lbs.

Available Conversion Types:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter a number (1-3) to select conversion or 4 to quit: 1
Enter the numerical value to convert: 440
Enter s

**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.
*   The program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers)
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
*   Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [3]:
def sum_numbers(nums):
  """
  This function calculates the total sum of elements in a given list.

  Arguments:
  nums (list): A collection of numerical values

  Returns:
  float: The computed sum of all elements in the list
  """
  return sum(nums)

def compute_average(nums):
  """
  This function determines the average (mean) of numbers in a list.

  Arguments:
  nums (list): A collection of numerical values

  Returns:
  float: The calculated mean of the provided numbers
  """
  return sum(nums) / len(nums)

def find_largest(nums):
  """
  This function identifies the highest value in a given list.

  Arguments:
  nums (list): A collection of numerical values

  Returns:
  float: The largest number present in the list
  """
  return max(nums)

def find_smallest(nums):
  """
  This function identifies the lowest value in a given list.

  Arguments:
  nums (list): A collection of numerical values

  Returns:
  float: The smallest number present in the list
  """
  return min(nums)

def main():
  """
  Primary function enabling users to select a mathematical operation and input data.
  Executes the selected operation and presents the outcome.
  Incorporates error handling for incorrect inputs and empty lists.
  """
  while True:
    print("\nAvailable Operations:")
    print("1. Calculate Total Sum")
    print("2. Compute Average")
    print("3. Identify Maximum Value")
    print("4. Identify Minimum Value")

    try:
      option = int(input("Select an operation or enter 5 to exit: "))

      if option == 5:
        print("Terminating the program.")
        break

      if option not in [1, 2, 3, 4]:
        print("Invalid choice. Kindly pick a valid option.")
        continue

      input_values = input("Provide numbers separated by spaces: ")
      num_list = [float(num) for num in input_values.split()]

      if not num_list:
        print("Error: At least one number is required.")
        continue

      if option == 1:
        result = sum_numbers(num_list)
        print(f"\nTotal Sum: {result}")
      elif option == 2:
        result = compute_average(num_list)
        print(f"\nAverage: {result}")
      elif option == 3:
        result = find_largest(num_list)
        print(f"\nMaximum Value: {result}")
      elif option == 4:
        result = find_smallest(num_list)
        print(f"\nMinimum Value: {result}")

    except ValueError:
      print("Error: Ensure you input valid numerical data.")
    except Exception as e:
      print(f"Unexpected issue encountered: {e}")

main()



Available Operations:
1. Calculate Total Sum
2. Compute Average
3. Identify Maximum Value
4. Identify Minimum Value
Select an operation or enter 5 to exit: 9
Invalid choice. Kindly pick a valid option.

Available Operations:
1. Calculate Total Sum
2. Compute Average
3. Identify Maximum Value
4. Identify Minimum Value
Select an operation or enter 5 to exit: 1
Provide numbers separated by spaces: 
Error: At least one number is required.

Available Operations:
1. Calculate Total Sum
2. Compute Average
3. Identify Maximum Value
4. Identify Minimum Value
Select an operation or enter 5 to exit: 1
Provide numbers separated by spaces: 3 5 1 4 6

Total Sum: 19.0

Available Operations:
1. Calculate Total Sum
2. Compute Average
3. Identify Maximum Value
4. Identify Minimum Value
Select an operation or enter 5 to exit: 2
Provide numbers separated by spaces: 2 4 6 8 12

Average: 6.4

Available Operations:
1. Calculate Total Sum
2. Compute Average
3. Identify Maximum Value
4. Identify Minimum Value

Exercise on list manipulation

1. Extract Every Other Element:

  Write a Python function that extracts every other element from a list, starting from the first element.

  Requirements:
- Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].


In [4]:
def every_other(num_list):
  return num_list[::2]

nums = [1, 2, 3, 4, 5, 6]
result = every_other(nums)
print(f"Every other elements of the list:\n{result}")


Alternate elements:
[1, 3, 5]


2. Slice a Sublist:

  Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Requirements:
- Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
- Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [6]:
def slice_list(items, start_idx, end_idx):
  return items[start_idx:end_idx+1]

numbers = [1, 2, 3, 4, 5, 6]
part = slice_list(numbers, 2, 4)
print(f"Selected portion from index 2 to 4:\n{part}")


Selected portion from index 2 to 4:
[3, 4, 5]


3. Reverse a List Using Slicing:

  Write a Python function that reverses a list using slicing.

  Requirements:
- Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [7]:
def reverse_elements(elements):
  return elements[::-1]

data = [1, 2, 3, 4, 5]
reversed_data = reverse_elements(data)
print(f"Reversed version of the list:\n{reversed_data}")


Reversed version of the list:
[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

  Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

  Requirements:
- Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [8]:
def remove_first_last(lst):
  return lst[1:-1]

input_list = [1, 2, 3, 4, 5]
sublist = remove_first_last(input_list)
print(f"List after removing first and last elements:\n{sublist}")

List after removing first and last elements:
[2, 3, 4]


5. Get the First n Elements:

  Write a Python function that extracts the first n elements from a list.

  Requirements:
- Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
- Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [9]:
def fetch_first_n(lst, n):
  return lst[:n]

numbers = [1, 2, 3, 4, 5]
count = 3
result = fetch_first_n(numbers, count)
print(f"First {count} elements of the list:\n{result}")


First 3 elements of the list:
[1, 2, 3]


6. Extract Elements from the End:

  Write a Python function that extracts the last n elements of a list using slicing.

  Requirements:
- Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
- Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [10]:
def last_n(lst, n):
  return lst[-n:]

numbers = [1, 2, 3, 4, 5]
count = 2
result = last_n(numbers, count)
print(f"Last {count} elements of the list:\n{result}")


Last 2 elements of the list:
[4, 5]


7. Extract Elements in Reverse Order:

  Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

  Requirements:
- Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [11]:
def skip_reverse(lst):
  return lst[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
result = skip_reverse(numbers)
print(f"Elements in reverse order:\n{result}")


Elements in reverse order:
[5, 3, 1]


## Exercise on Nested List:

1. Flatten a Nested List:

  Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

  Requirements:
- Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
- Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [12]:
def merge_lists(lst):
  merged = []
  for group in lst:
    for element in group:
      merged.append(element)
  return merged

nested_list = [[1, 2], [3, 4], [5]]
flat_list = merge_lists(nested_list)
print(f"Flattened list:\n{flat_list}")


Flattened list:
[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

  Write a Python function that extracts a specific element from a nested list given its indices.

  Requirements:
- Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
- Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [13]:
def get_nested_value(lst, keys):
  value = lst
  for key in keys:
    value = value[key]
  return value

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
position = [1, 2]
result = get_nested_value(nested_list, position)
print(f"Value at position {position}: {result}")


Value at position [1, 2]: 6


3. Sum of All Elements in a Nested List:

  Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

  Requirements:
- Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [14]:
def total_sum(lst):
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += total_sum(item)
    else:
      total += item
  return total

nested_numbers = [[1, 2], [3, [4, 5]], 6]
sum_result = total_sum(nested_numbers)
print(f"Total sum of all elements: {sum_result}")


Total sum of all elements: 21


4. Remove Specific Element from a Nested List:
  
  Write a Python function that removes all occurrences of a specific element from a nested list.

  Requirements:
- Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
- Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [15]:
def filter_element(lst, target):
  updated_list = []
  for item in lst:
    if isinstance(item, list):
      filtered_sublist = filter_element(item, target)
      if filtered_sublist:
        updated_list.append(filtered_sublist)
    elif item != target:
      updated_list.append(item)
  return updated_list

nested_list = [[1, 2], [3, 2], [4, 5]]
remove_value = 2
filtered_result = filter_element(nested_list, remove_value)
print(f"Updated list without {remove_value}:\n{filtered_result}")


Updated list without 2:
[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

  Write a Python function that finds the maximum element in a nested list (regardless of depth).

  Requirements:
- Define a function find max(lst) that takes a nested list lst and returns the maximum element.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [16]:
def get_max_value(lst):
  highest = float('-inf')
  for item in lst:
    if isinstance(item, list):
      highest = max(highest, get_max_value(item))
    else:
      highest = max(highest, item)
  return highest

nested_list = [[1, 2], [3, [4, 5]], 6]
max_number = get_max_value(nested_list)
print(f"Largest number in the list: {max_number}")


Largest number in the list: 6


6. Count Occurrences of an Element in a Nested List:

  Write a Python function that counts how many times a specific element appears in a nested list.

  Requirements:
- Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
- Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [17]:
def count_instances(lst, target):
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += count_instances(item, target)
    elif item == target:
      total += 1
  return total

nested_list = [[1, 2], [2, 3], [2, 4]]
search_element = 2
occurrences = count_instances(nested_list, search_element)
print(f"The number {search_element} appears {occurrences} times in the list.")


The number 2 appears 3 times in the list.


7. Flatten a List of Lists of Lists:

  Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

  Requirements:
- Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
- Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [18]:
def fully_flatten(lst):
  result = []
  for item in lst:
    if isinstance(item, list):
      result.extend(fully_flatten(item))
    else:
      result.append(item)
  return result

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flat_list = fully_flatten(nested_list)
print(f"Completely flattened list:\n{flat_list}")


Completely flattened list:
[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

  Write a Python function that calculates the average of all elements in a nested list.

  Requirements:
- Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
- Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [19]:
def compute_average(lst):
  def flatten_list(lst):
    result = []
    for item in lst:
      if isinstance(item, list):
        result.extend(flatten_list(item))
      else:
        result.append(item)
    return result

  numbers = flatten_list(lst)
  return sum(numbers) / len(numbers) if numbers else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
avg_value = compute_average(nested_list)
print(f"Average value of all elements: {avg_value}")


Average value of all elements: 3.5


Basic Vector and Matrix Operation with Numpy


Problem - 1: Array Creation:

In [20]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [21]:
import numpy as np

empty_arr = np.empty((2, 2))
print(f"Generated empty array:\n{empty_arr}")


Generated empty array:
[[6.77728652e-310 0.00000000e+000]
 [4.94065646e-324 6.77733111e-310]]


2. Initialize an all one array with size 4X2.

In [22]:
ones_arr = np.ones((4, 2))
print(f"Array filled with ones:\n{ones_arr}")


Array filled with ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.

In [23]:
arr = np.full((3,2), 5, dtype=int)
print(arr)

[[5 5]
 [5 5]
 [5 5]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [24]:
print(np.zeros_like(arr))

[[0 0]
 [0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
print(np.ones_like(arr))

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [25]:
new_list = [1, 2, 3, 4]
new_arr = np.array(new_list)

print(f"Numpy Array: {new_arr}")
print(f"Data Type: {type(new_arr)}")

Numpy Array: [1 2 3 4]
Data Type: <class 'numpy.ndarray'>


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [26]:
print(f"Array with values from 10 to 49:\n{np.arange(10, 49)}")

Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

In [27]:
array = np.arange(9)
matrix = np.reshape(array, (3, 3))

print(f"3×3 Matrix with values from 0 to 8:\n{matrix}")

3×3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [28]:
identity = np.eye(3, dtype=int)
print(f"3X3 identity matrix:\n{identity}")

3X3 identity matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [29]:
random_arr = np.random.random(30)
print(f"Random array of size 30:\n{random_arr}")
mean = np.mean(random_arr)
print(f"\nMean: {mean}")

Random array of size 30:
[0.11277932 0.32319332 0.57757484 0.87338579 0.56148223 0.67402954
 0.66038514 0.04839576 0.93024958 0.08028735 0.9943333  0.67377018
 0.20811639 0.24087443 0.12002131 0.64915361 0.78229436 0.27750469
 0.91408527 0.77213609 0.18620919 0.25400392 0.17189294 0.01412106
 0.91224882 0.57858584 0.01373047 0.11534749 0.50072708 0.70961998]

Mean: 0.4643513099395803


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [30]:
random_arr1 = np.random.random((10, 10))
print(f"10X10 array with random values:\n{random_arr1}")
print(f"\nMinimum value: {np.min(random_arr1)}")
print(f"\nMaximum value: {np.max(random_arr1)}")

10X10 array with random values:
[[0.91904684 0.72348283 0.71265687 0.51949653 0.30459601 0.2506402
  0.54680476 0.39052627 0.55652307 0.69331526]
 [0.8777355  0.54436984 0.8003569  0.73820447 0.03715625 0.18377891
  0.1319983  0.77548508 0.74541366 0.61521599]
 [0.80429117 0.42301902 0.58790728 0.29970744 0.87009162 0.4415267
  0.45716358 0.07590048 0.74185452 0.35002621]
 [0.87982515 0.48161187 0.9414139  0.97529623 0.05853771 0.83954805
  0.61514824 0.45000152 0.96512473 0.72032952]
 [0.74091558 0.15559592 0.3021566  0.60747031 0.49510122 0.42912085
  0.70251659 0.36666291 0.50348863 0.39650271]
 [0.43324094 0.33922433 0.04813495 0.0296393  0.14570852 0.54855804
  0.3320949  0.65365776 0.9382323  0.09410724]
 [0.43734734 0.20468258 0.17551507 0.04131643 0.45930992 0.97981951
  0.0918326  0.26771397 0.43432361 0.77237654]
 [0.01180529 0.21044419 0.72801249 0.16677625 0.36839215 0.30120916
  0.86263796 0.49103223 0.93456693 0.35332896]
 [0.80908719 0.95646913 0.8827554  0.79187699 0.95

6. Create a zero array of size 10 and replace 5th element with 1.

In [31]:
zeros_arr = np.zeros(10, dtype=int)
zeros_arr[4] = 1
print(zeros_arr)

[0 0 0 0 1 0 0 0 0 0]


7. Reverse an array arr = [1,2,0,0,4,0].

In [32]:
arr = np.array([1,2,0,0,4,0])
reversed = arr[::-1]
print(f"Reversed array: {reversed}")

Reversed array: [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [33]:
array = np.ones((7, 7), dtype=int)
array[1:-1, 1:-1] = 0

print("2D Array with 1 on the Border and 0 Inside:\n", array)

2D Array with 1 on the Border and 0 Inside:
 [[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [34]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("Generated 8x8 checkerboard pattern:\n", checkerboard)

Generated 8x8 checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:


1. Add two array

In [36]:
mat1 = np.array([[1, 2], [3, 5]])
mat2 = np.array([[5, 6], [7, 8]])
vec1 = np.array([9, 10])
vec2 = np.array([11, 12])

print("Matrix Addition Result:")
sum_matrices = np.add(mat1, mat2)
print(sum_matrices)

print("\nVector Addition Result:")
sum_vectors = np.add(vec1, vec2)
print(sum_vectors)

Matrix Addition Result:
[[ 6  8]
 [10 13]]

Vector Addition Result:
[20 22]


2. Subtract the two array.

In [39]:
print("Subtraction:")
result_xy = np.subtract(x, y)
print("Result of x - y:\n", result_xy)
print("")
result_vw = np.subtract(v, w)
print("Result of v - w:\n", result_vw)


Subtraction:
Result of x - y:
 [[-4 -4]
 [-4 -3]]

Result of v - w:
 [-2 -2]


3. Multiply the array with any integers of your choice.

In [38]:
print("Multiplication:")
result1 = np.dot(x, 2)
print("Result of multiplying x by 2:\n", result1)
print("")
result2 = np.dot(y, 3)
print("Result of multiplying y by 3:\n", result2)


Multiplication:
Result of multiplying x by 2:
 [[ 2  4]
 [ 6 10]]

Result of multiplying y by 3:
 [[15 18]
 [21 24]]


4. Find the square of each element of the array.

In [40]:
print("Square of each element:")
squared_x = x ** 2
print("Squared x:\n", squared_x)
print("")
squared_v = v ** 2
print("Squared v:\n", squared_v)


Square of each element:
Squared x:
 [[ 1  4]
 [ 9 25]]

Squared v:
 [ 81 100]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.



In [41]:
print("Dot Products:")
dot_prod_vw = np.dot(v, w)
print("\nDot product of v and w:", dot_prod_vw)

dot_prod_xv = np.dot(x, v)
print("\nDot product of x and v:\n", dot_prod_xv)

dot_prod_xy = np.dot(x, y)
print("\nDot product of x and y:\n", dot_prod_xy)


Dot Products:

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [42]:
print("Concatenating x and y along rows:")
concatenate_row = np.concatenate((x, y), axis=0)
print(concatenate_row)

print("\nConcatenating v and w along columns:")
concatenate_column = np.vstack((v, w)).T
print(concatenate_column)


Concatenating x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v and w along columns:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [44]:
print("\nConcatenating x and v:")
concatenate_xv = np.concatenate((x, v.reshape(1, -1)), axis=0)
print(concatenate_xv)



Concatenating x and v:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


### Problem - 4: Matrix Operations:
- For the following arrays:

  A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

  Prove following with Numpy:
  1. Prove A.A−1 = I.
  2. Prove AB ̸= BA.
  3. Prove(AB)T =BTAT.

In [46]:
A_mat = np.array([[3,4],[7,8]])
B_mat = np.array([[5,3],[2,1]])

from numpy import linalg

inv_A = np.linalg.inv(A_mat)
result = np.dot(A_mat, inv_A)
print(f"A * A⁻¹:\n{np.round(result)}")

AB = np.dot(A_mat, B_mat)
BA = np.dot(B_mat, A_mat)

if np.array_equal(A_mat, B_mat):
  print("\nAB = BA")
else:
  print("\nAB != BA")

AT = np.transpose(A_mat)
BT = np.transpose(B_mat)

BT_AT = np.dot(BT, AT)
AB_T = np.transpose(AB)

if np.array_equal(AB_T, BT_AT):
  print("\n(AB)ᵀ = Bᵀ Aᵀ")
else:
  print("\n(AB)ᵀ != Bᵀ Aᵀ")


A * A⁻¹:
[[1. 0.]
 [0. 1.]]

AB != BA

(AB)ᵀ = Bᵀ Aᵀ


- Solve the following system of Linear equation using Inverse Methods.

  2x − 3y + z = −1

  x − y + 2z = −3

  3x + y − z = 9

  {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [47]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Compute determinant of A
det_A = np.linalg.det(A)

# Compute adjugate matrix
cofactor_matrix = np.zeros_like(A, dtype=float)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
        cofactor_matrix[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)

adjugate_A = cofactor_matrix.T

# Compute inverse of A
A_inverse = adjugate_A / det_A

# Solve for X
X = np.dot(A_inverse, B)

print("\nSolution X:")
print(X)


Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Matrix B:
[-1 -3  9]

Solution X:
[ 2.  1. -2.]


- Now: solve the above equation using np.linalg.inv function. {Explore more about ”linalg” func- tion of Numpy}

In [48]:
matrix_A = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

matrix_B = np.array([-1, -3, 9])

inverse_A = np.linalg.inv(matrix_A)
solution_X = np.dot(inverse_A, matrix_B)

print("The solution vector X computed using the inverse function is:")
print(solution_X)


The solution vector X computed using the inverse function is:
[ 2.  1. -2.]


### Experiment: How Fast is Numpy?

1. Element-wise Addition:
- Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [49]:
import time
import numpy as np

# Creating large lists
list_1 = [i for i in range(1, 1000001)]
list_2 = [i for i in range(1000001, 2000001)]

# Measuring time for list-based addition
start_time = time.time()
result_list = [a + b for a, b in zip(list_1, list_2)]
end_time = time.time()
list_execution_time = end_time - start_time
print(f"Time taken for element-wise addition using Python lists: {list_execution_time:.6f} seconds")

# Converting lists to NumPy arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)

# Measuring time for NumPy array-based addition
start_time = time.time()
result_array = array_1 + array_2
end_time = time.time()
array_execution_time = end_time - start_time
print(f"Time taken for element-wise addition using NumPy arrays: {array_execution_time:.6f} seconds")


Time taken for element-wise addition using Python lists: 0.127799 seconds
Time taken for element-wise addition using NumPy arrays: 0.008366 seconds


2. Element-wise Multiplication
- Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [50]:
import time
import numpy as np

data1 = [i for i in range(1, 1000001)]
data2 = [i for i in range(1000001, 2000001)]

start_time = time.time()
output_list = [x * y for x, y in zip(data1, data2)]
end_time = time.time()
list_exec_time = end_time - start_time
print(f"Execution time for list-based element-wise multiplication: {list_exec_time} seconds")

array_a = np.array(data1)
array_b = np.array(data2)

start_time = time.time()
output_array = array_a * array_b
end_time = time.time()
array_exec_time = end_time - start_time
print(f"Execution time for NumPy array-based element-wise multiplication: {array_exec_time} seconds")


Execution time for list-based element-wise multiplication: 0.1212313175201416 seconds
Execution time for NumPy array-based element-wise multiplication: 0.007074117660522461 seconds


3. Dot Product
- Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [51]:
data1 = [i for i in range(1, 1000001)]
data2 = [i for i in range(1000001, 2000001)]

start_time = time.time()
dot_product_list = sum(x * y for x, y in zip(data1, data2))
end_time = time.time()
list_exec_time = end_time - start_time
print(f"Execution time for computing the dot product using lists: {list_exec_time} seconds")

array_a = np.array(data1)
array_b = np.array(data2)

start_time = time.time()
dot_product_numpy = np.dot(array_a, array_b)
end_time = time.time()
array_exec_time = end_time - start_time
print(f"Execution time for computing the dot product using NumPy: {array_exec_time} seconds")


Execution time for computing the dot product using lists: 0.11395549774169922 seconds
Execution time for computing the dot product using NumPy: 0.0017638206481933594 seconds


4. Matrix Multiplication
- Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea- sure and print the time taken for this operation.
- Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [53]:
size = 1000

mat1 = [[x + y for y in range(size)] for x in range(size)]
mat2 = [[x - y for y in range(size)] for x in range(size)]

def multiply_matrices(A, B):
    output = [[0] * size for _ in range(size)]
    for i in range(size):
        for j in range(size):
            for k in range(size):
                output[i][j] += A[i][k] * B[k][j]
    return output

start_time = time.time()
result_list = multiply_matrices(mat1, mat2)
end_time = time.time()
list_exec_time = end_time - start_time
print(f"Execution time for matrix multiplication using lists: {list_exec_time:.6f} seconds")

array_a = np.array(mat1)
array_b = np.array(mat2)

start_time = time.time()
result_numpy = np.dot(array_a, array_b)
end_time = time.time()
numpy_exec_time = end_time - start_time
print(f"Execution time for matrix multiplication using NumPy: {numpy_exec_time:.6f} seconds")


Execution time for matrix multiplication using lists: 199.177675 seconds
Execution time for matrix multiplication using NumPy: 1.681499 seconds
